ALTER TABLE posts ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE comments ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN deleted_at TIMESTAMP;